[colors.primary]
background = '#000000'
foreground = '#77DD77'

[font]
size = 15.0

[window]
decorations = "Buttonless"
dynamic_padding = true
startup_mode = "Fullscreen"

[terminal]
shell = "/bin/bash"
